### ISSUE TITLE
Ignore comments with graphql`` template literals

### ISSUE THREAD

**Issue by hanford** [cometkim/vite-plugin-relay-lite#188]
I have some code with a big comment in the code like this:

```
 *
 * <SelectAsync
 *   query={graphql`
 *     query {
 *       ....
 *   `}
 *   onChange={onChange}
 *
```

And currently the vite plugin tries (and fails) to apply the transformation, failing with an error like this:

```
x Build failed in 28.20s
[vite-plugin-relay-lite] Syntax Error: Unexpected character: "*".
file: //apps/dazzle/src/components/SelectAsyncDeprecated/index.tsx
    at syntaxError (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/error/syntaxError.js:15:10)
    at readNextToken (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/lexer.js:420:40)
    at Lexer.lookahead (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/lexer.js:84:29)
    at Lexer.advance (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/lexer.js:67:38)
    at Parser.advanceLexer (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1536:31)
    at Parser.expectToken (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1393:12)
    at Parser.many (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1507:10)
    at Parser.parseDocument (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:122:25)
    at parse (//node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:32:17)
    at //node_modules/.pnpm/vite-plugin-relay-lite@0.9.0_vite@5.4.10/node_modules/vite-plugin-relay-lite/src/compile.ts:54:17
    at getReplacement (//node_modules/.pnpm/magic-string@0.30.12/node_modules/magic-string/src/MagicString.js:794:12)
    at //node_modules/.pnpm/magic-string@0.30.12/node_modules/magic-string/src/MagicString.js:809:26
    at Array.forEach (<anonymous>)
    at MagicString._replaceRegexp (//node_modules/.pnpm/magic-string@0.30.12/node_modules/magic-string/src/MagicString.js:807:12)
    at MagicString.replace (//node_modules/.pnpm/magic-string@0.30.12/node_modules/magic-string/src/MagicString.js:851:15)
    at compile (//node_modules/.pnpm/vite-plugin-relay-lite@0.9.0_vite@5.4.10/node_modules/vite-plugin-relay-lite/src/compile.ts:43:11) {
  path: undefined,
  locations: [ { line: 2, column: 2 } ],
  extensions: [Object: null prototype] {},
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-relay-lite',
  hook: 'transform',
  id: '//src/components/SelectAsyncDeprecated/index.tsx',
  watchFiles: [
```

Ideally the plugin would ignore coded that's commented out!

**Comment by cometkim** [comment]
Yes, that's what I mentioned in README

> This plugin uses naive RegExp match instead of performing correct parsing for JavaScript. So it can fail on syntax that goes beyond the scope of a regular language. (e.g. queries in multiline comments)

Multi-line comments are something that cannot be reached due to the expressive limitations of regular expressions.

Perhaps I can fix by assuming it uses JSDoc-style, but there's no perfect solution for it.

**Comment by cometkim** [comment]
Imagine a `graphql` tag that uses `*` in somewhere in its own comments, I can't handle that ambiguity with only RegEx. So it would break some other projects.

**Comment by hanford** [comment]
Ahh, that makes sense! I can easily update my code. Feel free to close or keep open

**Comment by cometkim** [comment]
Assuming it's JSDoc (only "starts with" `*`), it seems safe. I'm adding test for it now

**Comment by cometkim** [comment]
Um, it may not.

Couldn't handle this properly without extra parsing

```graphql
      """
      * this should be compiled but...
      """
      query Test {
        # This should be compiled
        # // Even this
        __typename
      }
```
