### ISSUE TITLE
Vite 6.0 compatibility

### ISSUE THREAD

**Issue by hanford** [cometkim/vite-plugin-relay-lite#199]
Hello! me again :)

I've tried upgrading my applications to Vite 6.0 but I'm getting the following error:

```
[vite] Internal server error: graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`. Note also that there cannot be a space between graphql and the backtick that follows.
app                                          |       at invariant (/Users/hanford/Developer/app2/node_modules/.pnpm/invariant@2.2.4/node_modules/invariant/invariant.js:40:15)
app                                          |       at graphql (/Users/hanford/Developer/app2/node_modules/.pnpm/relay-runtime@18.0.0/node_modules/relay-runtime/lib/query/GraphQLTag.js:7:52)
app                                          |       at eval (/Users/hanford/Developer/app2/packages/design-system/hooks/useForethought.tsx:21:36)
app                                          |       at ESModulesEvaluator.runInlinedModule (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1053:5)
app                                          |       at SSRCompatModuleRunner.directRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1279:61)
app                                          |       at SSRCompatModuleRunner.directRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:30612:23)
app                                          |       at SSRCompatModuleRunner.cachedRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1174:76)
app                                          |       at eval (/Users/hanford/Developer/app2/packages/components/src/AuthenticatedUser/index.tsx:12:31)
app                                          |       at ESModulesEvaluator.runInlinedModule (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1053:5)
app                                          |       at SSRCompatModuleRunner.directRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1279:61)
app                                          |       at SSRCompatModuleRunner.directRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:30612:23)
app                                          |       at SSRCompatModuleRunner.cachedRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1174:76)
app                                          |       at eval (/Users/hanford/Developer/app2/apps/app/app/root.tsx:9:31)
app                                          |       at ESModulesEvaluator.runInlinedModule (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1053:5)
app                                          |       at SSRCompatModuleRunner.directRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/module-runner.js:1279:61)
app                                          |       at SSRCompatModuleRunner.directRequest (file:///Users/hanford/Developer/app2/node_modules/.pnpm/vite@6.0.2_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-A4nAWF7x.js:30612:23)
```

which implies that the transform isn't being run. I'm not sure if this is known or not, but I'll spend some time over the next couple of days creating a repro.

**Comment by cometkim** [comment]
Huh, thanks for reporting. I'll try myself tomorrow

**Comment by hanford** [comment]
`pnpm why graphql` [result](https://gist.github.com/hanford/528fa5a506c67ddaa6b031707c6c6f51)

(I'm in a very large monorepo)

I'm also working on a repro now, will share it soon

**Comment by hanford** [comment]
Hmmm, seems to be working in my repro. Sorry for the false alarm!

**Comment by hanford** [comment]
Yep, user error. My bad!
